GET http://localhost:4000/users

###

GET http://localhost:4000/users/12

###

POST http://localhost:4000/users
Content-Type: application/json

{
    "firstName": "olivier",
    "lastName": "chicheportiche",
    "email": "olivier.chicheportiche@gmail.com",
    "password": "password"
}

###

DELETE http://localhost:4000/users/63f8d1c33a2645cb48f43942
